version: '3.1'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 9411:9411
      - "5755:5755/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 5778:5778
      - 16686:16686
      - 14268:14268
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks: 
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring

networks: 
  tracing:
    external:
      name: monitoring