version: '3.4'

services:
  match.service:
    build:
      context: .
      dockerfile: src/Match.Service/Dockerfile.Debug
    networks:
      - monitoring
      - sample

  applicants.api:
    build:
      context: .
      dockerfile: src/Applicants.Api/Dockerfile.Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44335
    ports:
      - "12457:80"
      - "44335:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - monitoring
      - sample

  jobs.api:
    build:
      context: .
      dockerfile: src/Jobs.Api/Dockerfile.Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44334
    ports:
      - "12456:80"
      - "44334:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - monitoring
      - sample

  sample.web:
    build:
      context: .
      dockerfile: src/Sample.Web/Dockerfile.Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44336
    ports:
      - "12458:80"
      - "44336:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - monitoring
      - sample

      
networks:
  sample:
    external: 
      name: sample
  monitoring:
    external: 
      name: monitoring